### PR TITLE
 fix(datepicker): fix color of day of one-day range (#1980) 

### LINKED ISSUE #1980: [Datepicker] Fix color of selected day after #1972
I found that I missed the color style in the fix of #1972 

## Current Behavior

스크린샷 2019-10-01 오후 2 55 48

## Expected Behavior

The color of the selected day must be white

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v9.6.0  |
| React   |         |
| browser |  Firefox 70.0b8  |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

### PR DESCRIPTION
**Pull request by choyongjoon**
Fixes #1980

#### Description

First, I added `generateDayStyles` to reduce code size. Usually styles of 'start-of-month' and 'end-of-month' are same with default style. So I mereged these cases.

Then, I added color property to the two styles which were fixed in #1973 to fix #1980 

#### Scope

- [x] Patch: Bug Fix
- [ ] Minor: New Feature
- [ ] Major: Breaking Change

### CODE REVIEW

File: src/datepicker/styled-components.js [hunk 1]
```diff
@@ -228,68 +222,40 @@ function getDayStyles(code, {colors}) {
...
+    ...generateDayStyles('111010000000000', disabledDateStyle),
+    ...generateDayStyles('111000001010000', disabledDateStyle),
+    ...generateDayStyles('111000001001000', disabledDateStyle),
     // disabled pseudo-highlighted
-    '110000001100000': disabledDateStyle,
-    '110000001100100': disabledDateStyle,
-    '110000001100010': disabledDateStyle,
-    // range: selected date
+    ...generateDayStyles('110000001100000', disabledDateStyle),
+    // range: hovered date
```
Comment (nadiia) [inline src/datepicker/styled-components.js]:
```suggestion
    /// range: selected date
```
