### PR TITLE
fix(phone-input): add disabled property to country select

### LINKED ISSUE #1483: [PhoneInput] `disabled` state only partly disables the component
## Current Behavior

Setting `disabled` on the PhoneInput disables the text field part of the component, but the country icon with flags still opens on click. Selecting a country does not change the selected option though.

## Expected Behavior

The entire component to be in disabled/readonly mode. There should be no pointer on the flag and clicking should not be possible.

## Your Environment

| Tech    | Version |
| ------- | ------- |
| Base UI | v7.8.0  |
| React   |    16.8.6     |
| browser |    Chrome 75.x     |

- [x] I have searched the [issues](https://github.com/uber-web/baseui/issues) of this repository and believe that this is not a duplicate.

### PR DESCRIPTION
**Pull request by sandgraham**
Fixes #1483 

#### Description

This PR makes the Country Select in the Phone Input respect a top level `disabled` prop.

#### Scope

- [x] Patch: Bug Fix
- [ ] Minor: New Feature
- [ ] Major: Breaking Change

### CODE REVIEW

File: src/phone-input/types.js [hunk 1]
```diff
@@ -63,6 +63,7 @@ export type CountrySelectPropsT = {
   maxDropdownWidth?: string,
   maxDropdownHeight?: string,
   mapIsoToLabel?: mapIsoToLabelT,
+  disabled?: boolean,
```
Comment (gergelyke) [inline src/phone-input/types.js]: should we add a short description for it?
